version: '3.4'

services:
  Currencies.api:
    build:
      context: .
      dockerfile: Server/src/Currencies.Api/Dockerfile
    image: xbonioo/currencyapi
    ports:
      - "5000:80"
    environment:
      - COMPOSE_TLS_VERSION= "TLSv1_2"
    volumes:
      - ./logs:/src/logs
    depends_on:
      - database
  database:
    build: ./Server/src/Currencies.Api/mssql
    image: xbonioo/currency_database
    environment:
     ACCEPT_EULA: "Y"
     SA_PASSWORD: "Pwd12345"
     MSSQL_DB: "CurrenciesDB"
     MSSQL_USER: "user1"
     MSSQL_PASSWORD: "Pwd12345"
    ports:
     - "1433:1433"
    volumes:
      - ./mssql/data:/var/opt/mssql/data
      - ./mssql/config:/var/opt/mssql/config